components:
  schemas:
    Product:
      properties:
        _id:
          type: string
        category:
          type: string
        cost:
          type: number
        dimensions:
          type: string
        imageUrl:
          type: string
        isActive:
          type: boolean
        name:
          type: string
        price:
          type: number
        reorderLevel:
          type: integer
        sku:
          type: string
        stockQuantity:
          type: integer
        supplier:
          type: string
        targetStockLevel:
          type: integer
        unitOfMeasure:
          type: string
      type: object
  securitySchemes:
    bearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
info:
  description: Документация REST API для системы управления поставками
  title: Supplier Management API
  version: 1.0.0
openapi: 3.0.3
paths:
  /analytics/generate/daily:
    post:
      description: Создание аналитического отчета по заказам и продуктам за день.
      responses:
        '201':
          description: Отчет создан
        '500':
          description: Ошибка генерации
      security:
      - bearerAuth: []
      summary: Генерация ежедневной аналитики
      tags:
      - Analytics
  /auth/login:
    post:
      description: Получение JWT-токена после успешного входа.
      requestBody:
        content:
          application/json:
            schema:
              properties:
                email:
                  type: string
                password:
                  type: string
              type: object
        required: true
      responses:
        '200':
          description: Успешная аутентификация
        '401':
          description: Неверный логин или пароль
      summary: Аутентификация пользователя
      tags:
      - Auth
  /auth/register:
    post:
      description: Регистрация нового клиента, сотрудника или поставщика.
      requestBody:
        content:
          application/json:
            schema:
              properties:
                email:
                  format: email
                  type: string
                name:
                  type: string
                password:
                  type: string
                role:
                  type: string
              type: object
        required: true
      responses:
        '201':
          description: Успешная регистрация
        '400':
          description: Неверные данные
      summary: Регистрация пользователя
      tags:
      - Auth
  /clients:
    get:
      description: Доступно для менеджеров и администраторов
      responses:
        '200':
          description: Список клиентов
        '401':
          description: Неавторизован
        '403':
          description: Доступ запрещён
      security:
      - bearerAuth: []
      summary: Получить список клиентов
      tags:
      - Clients
  /employees:
    get:
      description: Доступно для авторизованных пользователей
      responses:
        '200':
          description: Список сотрудников
        '401':
          description: Неавторизован
      security:
      - bearerAuth: []
      summary: Получить список сотрудников
      tags:
      - Employees
    post:
      description: Создание записи о сотруднике
      requestBody:
        content:
          application/json:
            schema:
              properties:
                department:
                  type: string
                email:
                  type: string
                name:
                  type: string
                position:
                  type: string
              type: object
        required: true
      responses:
        '201':
          description: Сотрудник добавлен
        '400':
          description: Ошибка данных
      security:
      - bearerAuth: []
      summary: Добавить нового сотрудника
      tags:
      - Employees
  /orders:
    get:
      description: Возвращает список всех заказов. Доступно авторизованным пользователям.
      responses:
        '200':
          description: Список заказов
        '401':
          description: Неавторизован
      security:
      - bearerAuth: []
      summary: Получить все заказы
      tags:
      - Orders
    post:
      description: Создание заказа клиентом или менеджером.
      requestBody:
        content:
          application/json:
            schema:
              properties:
                client:
                  type: string
                deliveryDate:
                  format: date
                  type: string
                products:
                  items:
                    properties:
                      productId:
                        type: string
                      quantity:
                        type: integer
                    type: object
                  type: array
                status:
                  type: string
              type: object
        required: true
      responses:
        '201':
          description: Заказ создан
        '400':
          description: Ошибка валидации
        '401':
          description: Неавторизован
      security:
      - bearerAuth: []
      summary: Создать новый заказ
      tags:
      - Orders
  /products:
    post:
      description: Доступно для ролей admin и manager
      requestBody:
        content:
          application/json:
            schema:
              properties:
                category:
                  type: string
                cost:
                  type: number
                description:
                  type: string
                dimensions:
                  type: string
                imageUrl:
                  type: string
                isActive:
                  type: boolean
                name:
                  type: string
                price:
                  type: number
                reorderLevel:
                  type: integer
                sku:
                  type: string
                stockQuantity:
                  type: integer
                supplier:
                  type: string
                targetStockLevel:
                  type: integer
                unitOfMeasure:
                  type: string
              required:
              - name
              - sku
              - price
              - cost
              - supplier
              - stockQuantity
              type: object
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
          description: Успешное создание
        '400':
          description: Ошибка валидации
        '401':
          description: Неавторизован
        '403':
          description: Нет доступа
      security:
      - bearerAuth: []
      summary: Создание нового товара
      tags:
      - Products
  /suppliers:
    get:
      description: Доступно всем авторизованным пользователям
      responses:
        '200':
          description: Список поставщиков
        '401':
          description: Неавторизован
      security:
      - bearerAuth: []
      summary: Получить список поставщиков
      tags:
      - Suppliers
    post:
      description: Создание поставщика, доступно для администраторов
      requestBody:
        content:
          application/json:
            schema:
              properties:
                address:
                  type: string
                email:
                  type: string
                name:
                  type: string
                phone:
                  type: string
              type: object
        required: true
      responses:
        '201':
          description: Поставщик создан
        '400':
          description: Ошибка валидации
        '401':
          description: Неавторизован
      security:
      - bearerAuth: []
      summary: Добавить нового поставщика
      tags:
      - Suppliers
  /tasks:
    get:
      description: Доступно сотрудникам, менеджерам и администраторам
      responses:
        '200':
          description: Список задач
        '401':
          description: Неавторизован
        '403':
          description: Нет прав
      security:
      - bearerAuth: []
      summary: Получить все задачи
      tags:
      - Tasks
servers:
- description: Локальный сервер разработки
  url: http://localhost:5000/api
tags:
- description: Маршруты для управления сущностью admin
  name: Admin
- description: Маршруты для управления сущностью analytics
  name: Analytics
- description: Маршруты для управления сущностью auth
  name: Auth
- description: Маршруты для управления сущностью cart
  name: Cart
- description: Маршруты для управления сущностью clients
  name: Clients
- description: Маршруты для управления сущностью contracts
  name: Contracts
- description: Маршруты для управления сущностью employees
  name: Employees
- description: Маршруты для управления сущностью notifications
  name: Notifications
- description: Маршруты для управления сущностью orders
  name: Orders
- description: Маршруты для управления сущностью products
  name: Products
- description: Маршруты для управления сущностью reports
  name: Reports
- description: Маршруты для управления сущностью suppliers
  name: Suppliers
- description: Маршруты для управления сущностью tasks
  name: Tasks
